### ISSUE TITLE
Cannot import home config 

### ISSUE THREAD

**Issue by akb89** [annargrs/ldt#1] opened 2018-11-13 16:50 UTC
I am experiencing problems with config loading, and more specifically this part of the load_config.py file:
```
if "unittest" in sys.modules or "sphinx" in sys.modules:
    CONFIGPATH = TESTFILE
else:
    CONFIGPATH = os.path.expanduser('~/.ldt-config.yaml')
    if not os.path.exists(CONFIGPATH):
        print("Creating a sample configuration file in", CONFIGPATH)
        shutil.copyfile(TESTFILE, CONFIGPATH)
``` 
It turns out that 'unittest' is always loaded when doing an `import ldt`, so that it is impossible to enter the 'else' condition. 
I checked for `import unittest` code but couldn't find any outside of ldt tests. 
My guess would be that one of ldt dependencies is importing unittest outside of its test env. 
Note that the quick fix `del sys.modules['unittest']` does not work as unittest is loaded *during* 
`import ldt`.

**Comment by annargrs** [comment] 2018-11-13 20:50
Thanks for reporting this! Issue confirmed, I'll find where it gets imported (hopefully today/tomorrow). Also confirming that `del sys.modules['unittest']` no longer works.

**Comment by annargrs** [comment] 2018-11-14 16:49
Ok, this should be now fixed, please try the latest dev version with `pip install git+https://github.com/annargrs/ldt.git`

The problem was in sklearn - but I shouldn't have monopolized unittests in the first place, that is not robust with so many dependencies. Switched to a combination of local and Travis environment variables.

**Closed** 2018-11-17 21:09 UTC
Labels: bug
